### ISSUE TITLE
hasProperty not found method.

### ISSUE THREAD

**Issue by YunJooLee** [EPNW/solana_wallets_flutter#1]
Hi. 

I got error on build for ios. 
Just added dependency and import wallet, wallet-ui.

Problem is hasProperty and getProperty, Not found method or not defined method.

This is sample about error:

Error: Method not found: 'hasProperty'.
package:solana_wallets_flutter/src/adapter.dart:61
          hasProperty(js, 'connecting') &&
          ^^^^^^^^^^^

Error: The method 'getProperty' isn't defined for the class 'BaseWalletAdapter'.
package:solana_wallets_flutter/src/adapter.dart:76
- 'BaseWalletAdapter' is from 'package:solana_wallets_flutter/src/adapter.dart' ('../flutter/.pub-cache/hosted/pub.dartlang.org/solana_wallets_flutter-1.0.0/lib/src/adapter.dart').
package:solana_wallets_flutter/src/adapter.dart:1
    Try correcting the name to the name of an existing method, or defining a method named 'getProperty'.
      bool get _connected => getProperty(js, 'connected');

My flutter version is 3.1.0 and dart vesiont is 2.17.

**Comment by EP-u-NW** [comment]
This plugin only works for web, see [pub.dev](https://pub.dev/packages/solana_wallets_flutter)
